language: c
sudo: false
dist: trusty
env:
  global:
    - PATH=~/.roswell/bin:~/.linuxbrew/bin:$PATH
    - ROSWELL_BRANCH=release
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
    - ROSWELL_QUICKLISP_DIST_URI=https://github.com/roswell/quicklisp/releases/download/dist/quicklisp.txt
  matrix:
    - LISP=sbcl-bin

os:
  - linux

cache:
  directories:
    - $HOME/.rosproxy

install:
  - if ! [ -f "$HOME/.rosproxy/proxy" ]; then
      curl -L https://github.com/snmsts/roswell-proxy/releases/download/v0.5/v0.5-$TRAVIS_OS_NAME.tgz |tar xzf -;
      cp proxy $HOME/.rosproxy/proxy;
    fi
  - $HOME/.rosproxy/proxy daemon
  - mkdir ~/.roswell
  - echo "ros.proxy	0	localhost:5000" > ~/.roswell/config
  - echo "proxy.http.only	0	1" >> ~/.roswell/config
  - curl -L https://raw.githubusercontent.com/roswell/roswell/release/scripts/install-for-ci.sh | sh
  - ros install qlot

script:
  - make update
  - qlot install
  - make generate
  - git status
  - cat /tmp/proxy-log || true
  - pkill -9 proxy

after_success:
  - $HOME/.rosproxy/proxy daemon
  - pkill -9 proxy
