version: 2
jobs:
  build:
    docker:
      - image: nyangawa/roswell
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Clone origin/script
          command: git clone https://github.com/roswell/roswell.github.io.git -b script script
      - run:
          name: Update submodule
          command: git -C script submodule update --init --remote
      - run:
          name: Build website
          command: |
            rm *.html
            script/wiki2html.ros
            cp Home.html index.html
            cp script/style.css style.css
      - run:
          name: Push new website to origin/master
          command: |
            git add *.html 
            git commit -m 'Update documents' || :
            git push
workflows:
  version: 2
  commit-workflow:
    jobs:
      - build
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0 15 * * *"
          filters:
            branches:
              only: master
    jobs:
      - build
