version: 2
jobs:
  build:
    docker:
      - image: nyangawa/roswell
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Update submodule
          command: git submodule update --init --remote
      - run:
          name: Clone origin/master
          command: git clone https://github.com/roswell/roswell.github.io.git _public
      - run:
          name: Build website
          command: |
            rm -rf _public/*
            ./wiki2html.ros
            cp _public/Home.html _public/index.html
            cp style.css _public/style.css
      - run:
          name: Push new website to origin/master
          command: |
            git -C _public add *.html 
            git -C _public commit -m 'Update documents' || :
            git -C _public push
workflows:
  version: 2
  commit-workflow:
    jobs:
      - build
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0 15 * * *"
          filters:
            branches:
              only: ci
    jobs:
      - build
