version: 2
jobs:
  build:
    docker:
      - image: ubuntu:latest
    environment:
      LC_ALL: en_US.UTF-8
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Generate Locale files
          command: |
            apt-get update
            apt-get install -y locales
            locale-gen en_US.UTF-8 
      - run:
          name: Install latest roswell
          command: |
            apt-get update
            apt-get install -y curl jq git build-essential libcurl4-openssl-dev
            curl -sOL `curl -s https://api.github.com/repos/roswell/roswell/releases/latest | jq -r '.assets | .[] | select(.name|test("deb$")) | .browser_download_url'` 
            dpkg -i *.deb
      - run:
          name: Clone origin/script
          command: git clone https://github.com/roswell/roswell.github.io.git -b script script
      - run:
          name: Update submodule
          command: git -C script submodule update --init --remote
      - run:
          name: Build website
          command: |
            rm *.html
            script/wiki2html.ros
            cp Home.html index.html
            cp script/style.css style.css
      - run:
          name: Push new website to origin/master
          command: |
            git config --global user.email "ta2gch@users.noreply.github.com"
            git config --global user.name "TANIGUCHI Masaya"
            git add *.html 
            git commit -m 'Update documents' || :
            git push git@github:roswell/roswell.github.io HEAD:master
workflows:
  version: 2
  commit-workflow:
    jobs:
      - build
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0 15 * * *"
          filters:
            branches:
              only: master
    jobs:
      - build
